spring:
  config:
    import:
      - classpath:db-config/application-dev.yml
      - classpath:oauth-client-config/application-dev.yml
      - classpath:push-notification-config/application-dev.yml
      - classpath:kopis-client-config/application-dev.yml
      - classpath:global-cache-config/application-dev.yml
      - classpath:storage-config/application-dev.yml
      - optional:classpath:events-config/application-dev.yml
      - optional:classpath:observability-config/application-dev.yml
      - optional:secret

  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:100MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:100MB}

url:
  back:
    protocol: ${BACKEND_PROTOCOL:http}
    domain: ${BACKEND_DOMAIN:localhost:8080}
  front:
    protocol: ${FRONTEND_PROTOCOL:http}
    domain: ${FRONTEND_DOMAIN:localhost:5173}
    domain-name: ${FRONTEND_DOMAIN_NAME:localhost}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION:3600000}
    header: Authorization
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:1209600033}
    cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}

view:
  count:
    schedule:
      rate: ${VIEW_COUNT_SCHEDULE_RATE:3000}

thread-pool:
  task:
    core-size: ${THREAD_POOL_TASK_CORE_SIZE:10}
    max-size: ${THREAD_POOL_TASK_MAX_SIZE:20}
    queue-capacity: ${THREAD_POOL_TASK_QUEUE_CAPACITY:50}
  notification:
    core-size: ${THREAD_POOL_NOTIFICATION_CORE_SIZE:5}
    max-size: ${THREAD_POOL_NOTIFICATION_MAX_SIZE:10}
    queue-capacity: ${THREAD_POOL_NOTIFICATION_QUEUE_CAPACITY:30}
