spring:
  application:
    name: allreva-api
  config:
    import:
      - db.yml
      - oauth-client.yml
      - push-notification.yml
      - kopis-client.yml
      - global-cache.yml
      - storage.yml
      - observability.yml
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

view:
  count:
    schedule:
      rate: 3000

thread-pool:
  task:
    core-size: 10
    max-size: 20
    queue-capacity: 50
  notification:
    core-size: 5
    max-size: 10
    queue-capacity: 30

auth:
  jwt:
    access-token:
      header: Authorization
    refresh-token:
      name: refreshToken

---
spring:
  config:
    activate:
      on-profile: local

swagger:
  server:
    protocol: http
    domain: localhost:8080

cors:
  allowed-origin-patterns: http://localhost:5173

auth:
  jwt:
    secret-key: local-jwt-secret-key-must-be-long-enough-for-hmac-signing
    access-token:
      expiration: 3600000
    refresh-token:
      expiration: 1209600033
      cookie:
        domain: ""
        secure: false
        same-site: Lax

---
spring:
  config:
    activate:
      on-profile: dev

swagger:
  server:
    protocol: http
    domain: localhost:8080

cors:
  allowed-origin-patterns: http://localhost:5173

auth:
  jwt:
    secret-key: P2wW7hJW5VhWJXSqmSF4bnqn0g50NspypruwV8jOD5K0cpqmQjOduAdKvNaQ3xhk
    access-token:
      expiration: 3600000
    refresh-token:
      expiration: 1209600033
      cookie:
        domain: ""
        secure: true
        same-site: None

---
spring:
  config:
    activate:
      on-profile: "stag | prod"

swagger:
  server:
    protocol: ${SWAGGER_SERVER_PROTOCOL}
    domain: ${SWAGGER_SERVER_DOMAIN}

cors:
  allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS}

auth:
  jwt:
    secret-key: ${AUTH_JWT_SECRET_KEY}
    access-token:
      expiration: ${AUTH_JWT_ACCESS_TOKEN_EXPIRATION}
    refresh-token:
      expiration: ${AUTH_JWT_REFRESH_TOKEN_EXPIRATION}
      cookie:
        domain: ${AUTH_JWT_REFRESH_TOKEN_COOKIE_DOMAIN}
        secure: ${AUTH_JWT_REFRESH_TOKEN_COOKIE_SECURE}
        same-site: ${AUTH_JWT_REFRESH_TOKEN_COOKIE_SAME_SITE}
