name: '이슈 생성'
description: 'Repo에 이슈를 생성합니다.'
labels: [feat]
title: '이슈 이름을 작성해주세요'
body:
  - type: dropdown
    id: team-selection
    attributes:
      label: '👥 팀 선택 (Team)'
      description: '담당 팀을 선택해주세요'
      multiple: false
      options:
        - BE
        - FE
    validations:
      required: true

  - type: dropdown
    id: label-selection
    attributes:
      label: '🏷️ 라벨 선택 (Label)'
      description: '이슈의 성격에 맞는 라벨을 선택해주세요'
      multiple: false
      options:
        - FEAT
        - FIX
        - REFACTOR
        - CHORE
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '🌳 브랜치명 (Branch)'
      description: '영어로 브랜치명을 작성해주세요'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: '📝 상세 내용(Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '✅ 체크리스트(Tasks)'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
