management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics
  metrics:
    tags:
      application: ${spring.application.name}

loki:
  url: ${LOKI_URL}

logging:
  level:
    "[com.backend.allreva]": ${LOG_LEVEL_APP:INFO}
    "[org.springframework.web]": ${LOG_LEVEL_SPRING_WEB:WARN}
    "[org.hibernate.SQL]": ${LOG_LEVEL_HIBERNATE_SQL:OFF}
    "[org.hibernate.type.descriptor.sql.BasicBinder]": ${LOG_LEVEL_HIBERNATE_BINDER:OFF}
    "[org.springframework.security]": ${LOG_LEVEL_SPRING_SECURITY:WARN}
