spring:
  application:
    name: allreva-api
  profiles:
    active: dev
  config:
    import:
      - classpath:application-api.yml
      - classpath:application-infra.yml
      - optional:classpath:application-events.yml
      - optional:classpath:application-api-${spring.profiles.active}.yml
      - optional:classpath:application-infra-${spring.profiles.active}.yml
      - optional:classpath:application-events-${spring.profiles.active}.yml
      - optional:secret
