spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics
  metrics:
    tags:
      application: ${spring.application.name}

url:
  back:
    protocol: ${BACKEND_PROTOCOL:http}
    domain: ${BACKEND_DOMAIN:localhost:8080}
  front:
    protocol: ${FRONTEND_PROTOCOL:http}
    domain: ${FRONTEND_DOMAIN:localhost:5173}
    domain-name: ${FRONTEND_DOMAIN_NAME:localhost}

oauth2:
  kakao:
    redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:5173/auth/callback}
    client-id: ${KAKAO_CLIENT_ID:}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    api-url: https://kapi.kakao.com
    auth-url: https://kauth.kakao.com

jwt:
  secret_key: ${JWT_SECRET_KEY:}
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600033
    cookie-name: refreshToken

public-data:
  kopis:
    base-url: https://www.kopis.or.kr/openApi/restful
    service-key: ${KOPIS_SERVICE_KEY:}

view:
  count:
    schedule:
      rate: 3000

fcm:
  project-id: ${FCM_PROJECT_ID:}
  service-account-key: ${FCM_SERVICE_ACCOUNT_KEY_PATH:}

thread-pool:
  task:
    core-size: ${THREAD_POOL_TASK_CORE_SIZE:10}
    max-size: ${THREAD_POOL_TASK_MAX_SIZE:20}
    queue-capacity: ${THREAD_POOL_TASK_QUEUE_CAPACITY:50}
  notification:
    core-size: ${THREAD_POOL_NOTIFICATION_CORE_SIZE:5}
    max-size: ${THREAD_POOL_NOTIFICATION_MAX_SIZE:10}
    queue-capacity: ${THREAD_POOL_NOTIFICATION_QUEUE_CAPACITY:30}

loki:
  url: ${LOKI_URL:}

logging:
  level:
    "[com.backend.allreva]": ${LOG_LEVEL_APP:INFO}
    "[org.springframework.web]": ${LOG_LEVEL_SPRING_WEB:WARN}
    "[org.hibernate.SQL]": ${LOG_LEVEL_HIBERNATE_SQL:OFF}
    "[org.hibernate.type.descriptor.sql.BasicBinder]": ${LOG_LEVEL_HIBERNATE_BINDER:OFF}
