CREATE TABLE public.artist (
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    id character varying(255) NOT NULL,
    name character varying(255)
);

ALTER TABLE ONLY public.artist
    ADD CONSTRAINT artist_pkey PRIMARY KEY (id);



CREATE TABLE public.concert (
    eddate date NOT NULL,
    stdate date NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    view_count bigint NOT NULL,
    concert_code character varying(255) NOT NULL,
    hall_code character varying(255) NOT NULL,
    host character varying(255),
    poster character varying(255),
    prfstate character varying(255) NOT NULL,
    price text NOT NULL,
    time_table character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    detail_images jsonb NOT NULL,
    episodes jsonb NOT NULL,
    sellers jsonb NOT NULL,
    CONSTRAINT concert_prfstate_check CHECK (((prfstate)::text = ANY ((ARRAY['COMPLETED'::character varying, 'IN_PROGRESS'::character varying, 'SCHEDULED'::character varying])::text[])))
);

ALTER TABLE public.concert ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.concert_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.concert
    ADD CONSTRAINT concert_pkey PRIMARY KEY (id);

CREATE INDEX idx_hall_code ON public.concert USING btree (hall_code);



CREATE TABLE public.concert_hall (
    cafe boolean,
    elev_barrier boolean,
    latitude double precision,
    longitude double precision,
    park_barrier boolean,
    parking boolean,
    rest_barrier boolean,
    restaurant boolean,
    runw_barrier boolean,
    seat_scale integer NOT NULL,
    star double precision NOT NULL,
    store boolean,
    review_count bigint NOT NULL,
    total_stars bigint NOT NULL,
    address character varying(255) NOT NULL,
    id character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE ONLY public.concert_hall
    ADD CONSTRAINT concert_hall_pkey PRIMARY KEY (id);



CREATE TABLE public.member (
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    introduce character varying(255),
    nickname character varying(255) NOT NULL,
    profile_image_url character varying(255) NOT NULL,
    provider character varying(255) NOT NULL,
    refund_account character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT member_provider_check CHECK (((provider)::text = ANY ((ARRAY['KAKAO'::character varying, 'GOOGLE'::character varying, 'ORIGINAL'::character varying])::text[]))),
    CONSTRAINT member_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'DEVELOPER'::character varying])::text[])))
);

ALTER TABLE public.member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);



CREATE TABLE public.member_artist (
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    artist_id character varying(255) NOT NULL
);

ALTER TABLE public.member_artist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_artist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.member_artist
    ADD CONSTRAINT member_artist_pkey PRIMARY KEY (id);



CREATE TABLE public.notification (
    is_read boolean NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    recipient_id bigint,
    room_id bigint,
    sender_id bigint,
    updated_at timestamp(6) without time zone,
    message character varying(255),
    room_name character varying(255),
    sender_name character varying(255),
    title character varying(255),
    type character varying(255),
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY ((ARRAY['CHAT_MESSAGE'::character varying, 'CHAT_MEMBER_JOINED'::character varying, 'CHAT_MEMBER_LEFT'::character varying, 'RENT_REGISTERED'::character varying, 'RENT_PARTICIPANT_JOINED'::character varying, 'RENT_CANCELLED'::character varying, 'SURVEY_REGISTERED'::character varying, 'SURVEY_RESPONSE_RECEIVED'::character varying, 'SURVEY_CLOSED'::character varying, 'CONCERT_REMINDER'::character varying, 'CONCERT_UPDATED'::character varying, 'DIARY_LIKE_RECEIVED'::character varying, 'DIARY_COMMENT_RECEIVED'::character varying, 'GENERAL'::character varying])::text[])))
);

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);



CREATE TABLE public.rent (
    end_date date NOT NULL,
    is_closed boolean NOT NULL,
    max_passenger integer NOT NULL,
    price integer NOT NULL,
    concert_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    artist_name character varying(255) NOT NULL,
    boarding_type character varying(255) NOT NULL,
    bus_size character varying(255) NOT NULL,
    bus_type character varying(255) NOT NULL,
    image character varying(255) NOT NULL,
    information character varying(255),
    region character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    up_boarding_area character varying(255),
    up_drop_off_area character varying(255),
    up_time character varying(255),
    down_boarding_area character varying(255),
    down_drop_off_area character varying(255),
    down_time character varying(255),
    CONSTRAINT rent_boarding_type_check CHECK (((boarding_type)::text = ANY ((ARRAY['ROUND'::character varying, 'UP'::character varying, 'DOWN'::character varying])::text[]))),
    CONSTRAINT rent_bus_size_check CHECK (((bus_size)::text = ANY ((ARRAY['LARGE'::character varying, 'MEDIUM'::character varying, 'MINI'::character varying])::text[]))),
    CONSTRAINT rent_bus_type_check CHECK (((bus_type)::text = ANY ((ARRAY['STANDARD'::character varying, 'DELUXE'::character varying, 'PREMIUM'::character varying])::text[])))
);

ALTER TABLE public.rent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.rent
    ADD CONSTRAINT rent_pkey PRIMARY KEY (id);



CREATE TABLE public.rent_boarding_slots (
    date date NOT NULL,
    passenger_count integer NOT NULL,
    recruitment_count integer NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    rent_id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.rent_boarding_slots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rent_boarding_slots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.rent_boarding_slots
    ADD CONSTRAINT rent_boarding_slots_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.rent_boarding_slots
    ADD CONSTRAINT fk_rent_boarding_slots_rent FOREIGN KEY (rent_id) REFERENCES public.rent(id);

CREATE INDEX idx_rent_boarding_slots_rent_date ON public.rent_boarding_slots USING btree (rent_id, date);



CREATE TABLE public.rent_participants (
    boarding_date date NOT NULL,
    passenger_num integer NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    rent_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    depositor_name character varying(255) NOT NULL,
    depositor_time character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    refund_account character varying(255) NOT NULL,
    refund_type character varying(255) NOT NULL,
    CONSTRAINT rent_participants_refund_type_check CHECK (((refund_type)::text = ANY ((ARRAY['ADDITIONAL_DEPOSIT'::character varying, 'REFUND'::character varying, 'BOTH'::character varying])::text[])))
);

ALTER TABLE public.rent_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rent_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.rent_participants
    ADD CONSTRAINT rent_participants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.rent_participants
    ADD CONSTRAINT fk_rent_participants_rent FOREIGN KEY (rent_id) REFERENCES public.rent(id);



CREATE TABLE public.seat_review (
    star integer NOT NULL,
    view_date date NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    concert_title character varying(255) NOT NULL,
    content character varying(255),
    hall_id character varying(255) NOT NULL,
    seat character varying(255) NOT NULL,
    CONSTRAINT seat_review_star_check CHECK (((star >= 0) AND (star <= 5)))
);

ALTER TABLE public.seat_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seat_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.seat_review
    ADD CONSTRAINT seat_review_pkey PRIMARY KEY (id);



CREATE TABLE public.seat_review_image (
    order_num integer NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    seat_review_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    url character varying(255) NOT NULL
);

ALTER TABLE public.seat_review_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seat_review_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.seat_review_image
    ADD CONSTRAINT seat_review_image_pkey PRIMARY KEY (id);



CREATE TABLE public.seat_review_like (
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    review_id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.seat_review_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seat_review_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.seat_review_like
    ADD CONSTRAINT seat_review_like_pkey PRIMARY KEY (id);

CREATE INDEX idx_review_member ON public.seat_review_like USING btree (review_id, member_id);



CREATE TABLE public.survey (
    eddate date NOT NULL,
    is_closed boolean NOT NULL,
    max_passenger integer NOT NULL,
    region smallint NOT NULL,
    concert_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    artist_name character varying(255) NOT NULL,
    information character varying(255),
    title character varying(255) NOT NULL,
    boarding_dates jsonb NOT NULL,
    CONSTRAINT survey_region_check CHECK (((region >= 0) AND (region <= 18)))
);

ALTER TABLE public.survey ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.survey
    ADD CONSTRAINT survey_pkey PRIMARY KEY (id);



CREATE TABLE public.survey_participants (
    boarding_date date NOT NULL,
    notified boolean NOT NULL,
    passenger_num integer NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    survey_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    boarding_type character varying(255) NOT NULL,
    CONSTRAINT survey_participants_boarding_type_check CHECK (((boarding_type)::text = ANY ((ARRAY['ROUND'::character varying, 'UP'::character varying, 'DOWN'::character varying])::text[])))
);

ALTER TABLE public.survey_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.survey_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.survey_participants
    ADD CONSTRAINT survey_participants_pkey PRIMARY KEY (id);
