spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    aws:
      s3:
        bucket: local-allreva-bucket
      credentials:
        access-key: local-aws-access-key
        secret-key: local-aws-secret-key

---
spring:
  config:
    activate:
      on-profile: "stag | prod"
  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
